# Generated by Django 3.2.16 on 2023-01-27 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_admin', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_admin', models.CharField(max_length=16, null=True)),
                ('nombre_admin', models.CharField(max_length=64, null=True)),
                ('apellidoP_admin', models.CharField(max_length=64, null=True)),
                ('apellidoM_admin', models.CharField(max_length=64, null=True)),
                ('email_admin', models.CharField(max_length=64, null=True)),
                ('direccion_admin', models.CharField(max_length=64, null=True)),
                ('contrasena_admin', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_cliente', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_cliente', models.CharField(max_length=16, null=True)),
                ('nombre_cliente', models.CharField(max_length=64, null=True)),
                ('apellidoP_Cliente', models.CharField(max_length=64, null=True)),
                ('apellidoM_Cliente', models.CharField(max_length=64, null=True)),
                ('email_cliente', models.CharField(max_length=64, null=True)),
                ('direccion_cliente', models.CharField(max_length=64, null=True)),
                ('contrasena_cliente', models.CharField(max_length=80, null=True)),
                ('estado_cliente', models.BooleanField(default=True)),
                ('tipo_cliente', models.CharField(choices=[('Natural', 'Natural'), ('Juridica', 'Juridica')], default='Natural', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_factura', models.IntegerField()),
                ('lectura_factura', models.IntegerField()),
                ('total_factura', models.IntegerField()),
                ('date_crea_factu', models.DateField()),
                ('date_ven_factu', models.DateField()),
                ('periodo_factu', models.DateField()),
                ('estado_factura', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id_gerente', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_gerente', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_gerente', models.CharField(max_length=16, null=True)),
                ('nombre_gerente', models.CharField(max_length=64, null=True)),
                ('apellidoP_Gerente', models.CharField(max_length=64, null=True)),
                ('apellidoM_Gerente', models.CharField(max_length=64, null=True)),
                ('email_gerente', models.CharField(max_length=64, null=True)),
                ('direccion_gerente', models.CharField(max_length=64, null=True)),
                ('contrasena_gerente', models.CharField(max_length=80, null=True)),
                ('estado_gerente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id_operador', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_operador', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_operador', models.CharField(max_length=16, null=True)),
                ('nombre_operador', models.CharField(max_length=64, null=True)),
                ('apellidoP_Operador', models.CharField(max_length=64, null=True)),
                ('apellidoM_Operador', models.CharField(max_length=64, null=True)),
                ('email_operador', models.CharField(max_length=64, null=True)),
                ('direccion_operador', models.CharField(max_length=64, null=True)),
                ('contrasena_operador', models.CharField(max_length=80, null=True)),
                ('estado_operador', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagoejemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagar', models.CharField(max_length=12)),
                ('cedula', models.IntegerField(blank=True, default=0, null=True)),
                ('total_pago', models.CharField(max_length=12)),
                ('operador', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicios', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], default='Residencial', max_length=12)),
                ('estado_servicio', models.BooleanField(default=True)),
                ('mora_servicio', models.BooleanField(default=False)),
                ('direccion_servicio', models.CharField(max_length=64, null=True)),
                ('fecha_creacion', models.DateField(default='2022/12/22')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usmelectrica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Banco', 'Banco'), ('Virtual', 'Virtual')], default='Presencial', max_length=12, null=True)),
                ('total_pago', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_pago', models.DateField(blank=True, default=datetime.date(2023, 1, 27), null=True)),
                ('factura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usmelectrica.factura')),
                ('operador_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usmelectrica.operador')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usmelectrica.servicio'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_estado', models.CharField(max_length=100)),
                ('total_de_la_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_cliente', models.CharField(max_length=64)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('correo_cliente', models.EmailField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=64)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usmelectrica.producto')),
            ],
        ),
    ]
